---
bool running
bool stop_requested
bool has_system
bool shutdown_requested
bool worker_alive
string worker_exception
int32 tracking_state
string tracking_state_name
uint64 tracked_map_points
uint64 pending_size
uint64 pending_queue_size
uint64 pending_drop_count
uint64 expired_drop_count
uint64 processed_obs_count
uint64 rx_obs_count
uint64 enqueued_obs_count
uint64 ignored_obs_count
uint64 ignored_inactive_count
uint64 ignored_not_configured_count
uint64 ignored_stopping_count
uint64 ignored_no_backend_count
uint64 ignored_mode_mismatch_count
uint64 track_result_count
uint64 no_pose_count
uint64 pose_published_count
builtin_interfaces/Time last_observation_stamp
uint64 last_observation_t_track_ns
int64 last_observation_dt_ns
uint64 memory_rss_kb
uint64 track_time_us_last
